version: '3.3'

services:
  elasticsearch:
    build: dockerfiles/elasticsearch
    image: elasticsearch
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    restart: unless-stopped
    environment:
      - "cluster.name=elasticsearch-node-abyss"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - abyssnet
    volumes:
      - ./data/logs/elasticsearch:/usr/share/elasticsearch/logs
      - ./data/config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
  elastichd:
    image: containerize/elastichd
    container_name: elastichd
    ports:
      - 9800:9800
    restart: unless-stopped
    links: 
      - elasticsearch
    networks:
      - abyssnet
    depends_on: 
      - elasticsearch

networks:
  abyssnet: