{
 "title": "[InfluxDB] 5m downsample",
 "tags": [
  "Percona",
  "InfluxDB"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": "SHOW TAG VALUES WITH KEY=alias" }
  ]
 },
 "panels": [
  { "title": "5m downsample", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MySQL Connections and Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Queries",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "5m" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "5m\".\"mysql_global_status_queries",
     "query": "SELECT non_negative_derivative(max(\"max\"), 1s) FROM \"5m\".\"mysql_global_status_queries\" WHERE \"alias\" = '$host' AND $timeFilter GROUP BY time(5m), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" }
     ]
    },
    {
     "alias": "Connections",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "5m" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "5m\".\"mysql_global_status_connections",
     "query": "SELECT non_negative_derivative(max(\"max\"), 1s) FROM \"5m\".\"mysql_global_status_connections\" WHERE \"alias\" = '$host' AND $timeFilter GROUP BY time(5m), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" }
     ]
    }
   ]
  },
  {
   "title": "MySQL Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Inbound",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "5m" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "5m\".\"mysql_global_status_bytes_received",
     "query": "SELECT non_negative_derivative(max(\"max\"), 1s) FROM \"5m\".\"mysql_global_status_bytes_received\" WHERE \"alias\" = '$host' AND $timeFilter GROUP BY time(5m), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" }
     ]
    },
    {
     "alias": "Outbound",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "5m" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "5m\".\"mysql_global_status_bytes_sent",
     "query": "SELECT non_negative_derivative(max(\"max\"), 1s) FROM \"5m\".\"mysql_global_status_bytes_sent\" WHERE \"alias\" = '$host' AND $timeFilter GROUP BY time(5m), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" }
     ]
    }
   ]
  },
  {
   "title": "MySQL Network Usage Hourly",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Received",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "1h" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "1h\".\"mysql_global_status_bytes_received",
     "query": "SELECT non_negative_derivative(max(\"max\"), 1h) FROM \"1h\".\"mysql_global_status_bytes_received\" WHERE \"alias\" = '$host' AND $timeFilter GROUP BY time(1h), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1h" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" }
     ]
    },
    {
     "alias": "Sent",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "1h" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "1h\".\"mysql_global_status_bytes_sent",
     "query": "SELECT non_negative_derivative(max(\"max\"), 1h) FROM \"1h\".\"mysql_global_status_bytes_sent\" WHERE \"alias\" = '$host' AND $timeFilter GROUP BY time(1h), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1h" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" }
     ]
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Size: $tag_mountpoint (device $tag_device)",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "5m" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "mountpoint" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "fstype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "5m\".\"node_filesystem_size",
     "query": "SELECT mean(\"mean\") FROM \"5m\".\"node_filesystem_size\" WHERE \"alias\" = '$host' AND \"mountpoint\" !~ /^\\/var\\/named/ AND \"fstype\" !~ /rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs/ AND $timeFilter GROUP BY time(5m), \"alias\", \"mountpoint\", \"device\", \"fstype\" fill(null)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "mountpoint", "operator": "!~", "value": "/^\\/var\\/named/" },
      {
       "condition": "AND",
       "key": "fstype",
       "operator": "!~",
       "value": "/rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs/"
      }
     ]
    },
    {
     "alias": "Free: $tag_mountpoint (device $tag_device)",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "5m" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "mountpoint" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "fstype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "5m\".\"node_filesystem_avail",
     "query": "SELECT mean(\"mean\") FROM \"5m\".\"node_filesystem_avail\" WHERE \"alias\" = '$host' AND \"mountpoint\" !~ /^\\/var\\/named/ AND \"fstype\" !~ /rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs/ AND $timeFilter GROUP BY time(5m), \"alias\", \"mountpoint\", \"device\", \"fstype\" fill(null)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "mountpoint", "operator": "!~", "value": "/^\\/var\\/named/" },
      {
       "condition": "AND",
       "key": "fstype",
       "operator": "!~",
       "value": "/rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs/"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Read: $tag_device",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "5m" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "5m\".\"node_disk_reads_completed",
     "query": "SELECT non_negative_derivative(max(\"max\"), 1s) FROM \"5m\".\"node_disk_reads_completed\" WHERE \"alias\" = '$host' AND $timeFilter GROUP BY time(5m), \"alias\", \"device\" fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" }
     ]
    },
    {
     "alias": "Write: $tag_device",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "5m" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "5m\".\"node_disk_writes_completed",
     "query": "SELECT non_negative_derivative(max(\"max\"), 1s) FROM \"5m\".\"node_disk_writes_completed\" WHERE \"alias\" = '$host' AND $timeFilter GROUP BY time(5m), \"alias\", \"device\" fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" }
     ]
    }
   ]
  },
  {
   "title": "Disk Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Read: $tag_device",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "5m" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "5m\".\"node_disk_bytes_read",
     "query": "SELECT non_negative_derivative(max(\"max\"), 1s) FROM \"5m\".\"node_disk_bytes_read\" WHERE \"alias\" = '$host' AND $timeFilter GROUP BY time(5m), \"alias\", \"device\" fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" }
     ]
    },
    {
     "alias": "Write: $tag_device",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "5m" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "5m\".\"node_disk_bytes_written",
     "query": "SELECT non_negative_derivative(max(\"max\"), 1s) FROM \"5m\".\"node_disk_bytes_written\" WHERE \"alias\" = '$host' AND $timeFilter GROUP BY time(5m), \"alias\", \"device\" fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_mode",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "5m" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "mode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "5m\".\"node_cpu",
     "query": "SELECT non_negative_derivative(sum(\"max\"), 1s)  * 100 FROM \"5m\".\"node_cpu\" WHERE \"alias\" = '$host' AND $timeFilter GROUP BY time(5m), \"alias\", \"mode\" fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" }
     ]
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Load",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "5m" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "5m\".\"node_load1",
     "query": "SELECT mean(\"mean\") FROM \"5m\".\"node_load1\" WHERE \"alias\" = '$host' AND $timeFilter GROUP BY time(5m), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Total Size",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "5m" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "5m\".\"node_memory_MemTotal",
     "query": "SELECT mean(\"mean\") FROM \"5m\".\"node_memory_MemTotal\" WHERE \"alias\" = '$host' AND $timeFilter GROUP BY time(5m), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" }
     ]
    },
    {
     "alias": "Free",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "5m" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "5m\".\"node_memory_MemFree",
     "query": "SELECT mean(\"mean\") FROM \"5m\".\"node_memory_MemFree\" WHERE \"alias\" = '$host' AND $timeFilter GROUP BY time(5m), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" }
     ]
    },
    {
     "alias": "Cached",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "5m" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "5m\".\"node_memory_Cached",
     "query": "SELECT mean(\"mean\") FROM \"5m\".\"node_memory_Cached\" WHERE \"alias\" = '$host' AND $timeFilter GROUP BY time(5m), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" }
     ]
    },
    {
     "alias": "Buffers",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "5m" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "5m\".\"node_memory_Buffers",
     "query": "SELECT mean(\"mean\") FROM \"5m\".\"node_memory_Buffers\" WHERE \"alias\" = '$host' AND $timeFilter GROUP BY time(5m), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" }
     ]
    },
    {
     "alias": "Available",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "5m" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "5m\".\"node_memory_MemAvailable",
     "query": "SELECT mean(\"mean\") FROM \"5m\".\"node_memory_MemAvailable\" WHERE \"alias\" = '$host' AND $timeFilter GROUP BY time(5m), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Inbound: $tag_device",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "5m" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "5m\".\"node_network_receive_bytes",
     "query": "SELECT non_negative_derivative(max(\"max\"), 1s) FROM \"5m\".\"node_network_receive_bytes\" WHERE \"alias\" = '$host' AND \"device\" <> 'lo' AND $timeFilter GROUP BY time(5m), \"alias\", \"device\" fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "device", "operator": "<>", "value": "lo" }
     ]
    },
    {
     "alias": "Outbound: $tag_device",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "5m" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "5m\".\"node_network_transmit_bytes",
     "query": "SELECT non_negative_derivative(max(\"max\"), 1s) FROM \"5m\".\"node_network_transmit_bytes\" WHERE \"alias\" = '$host' AND \"device\" <> 'lo' AND $timeFilter GROUP BY time(5m), \"alias\", \"device\" fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "device", "operator": "<>", "value": "lo" }
     ]
    }
   ]
  },
  {
   "title": "Network Usage Hourly",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Received",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "1h" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "1h\".\"node_network_receive_bytes",
     "query": "SELECT non_negative_derivative(sum(\"max\"), 1h) FROM \"1h\".\"node_network_receive_bytes\" WHERE \"alias\" = '$host' AND \"device\" <> 'lo' AND $timeFilter GROUP BY time(1h), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1h" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "device", "operator": "<>", "value": "lo" }
     ]
    },
    {
     "alias": "Sent",
     "calculatedInterval": "2m",
     "groupBy": [
      { "interval": "auto", "params": [ "1h" ], "type": "time" },
      { "key": "alias", "params": [ "alias" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ alias }}",
     "measurement": "1h\".\"node_network_transmit_bytes",
     "query": "SELECT non_negative_derivative(sum(\"max\"), 1h) FROM \"1h\".\"node_network_transmit_bytes\" WHERE \"alias\" = '$host' AND \"device\" <> 'lo' AND $timeFilter GROUP BY time(1h), \"alias\" fill(null)",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1h" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "alias", "operator": "=", "value": "$host" },
      { "condition": "AND", "key": "device", "operator": "<>", "value": "lo" }
     ]
    }
   ]
  }
 ]
}