version: '3.3'

# monitor swarm
# by Abyss
# roger_ren@qq.com
# 部署研究下labels, 部署到固定的主机名/群/组
# 研究下traefik 反向代理
services:
  # 时序数据库 influxdb 1.2有图形界面
  # 默认数据保持7天
  # 需要持久化  - db
  # 默认用户名admin/admin
  # 数据库名字cadvisor
  # httpd端口 - 8086
  # 图形管理端口  - 8083
  influx:
    # image: abyss/influxdb
    image: influxdb:1.2
    networks:
      - net_grafana
    ports:
      - 0.0.0.0:8086:8086
      - 0.0.0.0:8083:8083
    volumes:
      - influx:/var/lib/influxdb
    environment:
      TZ: Asia/Shanghai
      INFLUXDB_DB: cadvisor
      INFLUXDB_ADMIN_ENABLED: 1
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: r61553757
      INFLUXDB_USER: admin
      INFLUXDB_USER_PASSWORD: r61553757
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 2g
          cpus: "10.00"

  # 数据展示 grafana 6.0.0
  # 数据源多样
  # 默认用户名admin/admin
  # 需要持久化  - dashboard
  # 需要持久化  - config
  # 需要持久化  - users
  # 研究下 es与日志分析
  grafana:
    # image: abyss/grafana
    image: grafana/grafana:6.0.0
    ports:
      - 0.0.0.0:3000:3000
    networks:
      - net_grafana
    depends_on:
      - influx
    volumes:
      - grafana:/var/lib/grafana
    environment:
      TZ: Asia/Shanghai
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 1g
          cpus: "3.00"

  # 系统监控 cadvisor
  # 管理端口  - 19998
  cadvisor:
    # image: abyss/cadvisor
    image: google/cadvisor
    hostname: '{{.Node.Hostname}}'
    networks:
      - net_grafana
    ports:
      - 0.0.0.0:19998:8080
    command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influx:8086
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - influx
    deploy:
      mode: global
      resources:
        limits:
          memory: 256m
          cpus: "3.00"

  # 容器管理 portainer
  # 管理端口  - 9000
  portainer:
    image: portainer/portainer
    ports:
      - 0.0.0.0:9000:9000
    networks:
      - net_grafana
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    environment:
      TZ: Asia/Shanghai
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 256m
          cpus: "2.00"

# 网络研究中
# 覆盖网络会到每个节点
networks:
  net_grafana:
    driver: overlay

# 本地磁盘
# 持久化方案研究中
# 分布式同步方案
# 容灾备份
volumes:
  influx:
    driver: local
  grafana:
    driver: local
  portainer:
    driver: local