version: '3'

services:
  nginx:
    image: nginx:1.15.9
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped