version: '3.3'

services:
  influx:
    # image: abyss/influxdb
    image: influxdb:1.2
    networks:
      - net_grafana
    ports:
      - 0.0.0.0:8086:8086
      - 0.0.0.0:8083:8083
    volumes:
      - influx:/var/lib/influxdb
    environment:
      TZ: Asia/Shanghai
      INFLUXDB_DB: cadvisor
      INFLUXDB_ADMIN_ENABLED: 1
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: admin
      INFLUXDB_USER_PASSWORD: admin
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 2g
          cpus: "10.00"

  grafana:
    # image: abyss/grafana
    image: grafana/grafana:6.0.0
    ports:
      - 0.0.0.0:80:3000
    networks:
      - net_grafana
    depends_on:
      - influx
    volumes:
      - grafana:/var/lib/grafana
    environment:
      TZ: Asia/Shanghai
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 1g
          cpus: "3.00"

  cadvisor:
    # image: abyss/cadvisor
    image: google/cadvisor
    hostname: '{{.Node.Hostname}}'
    networks:
      - net_grafana
    ports:
      - 0.0.0.0:19998:8080
    command: -logtostderr -docker_only -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influx:8086
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - influx
    deploy:
      mode: global
      resources:
        limits:
          memory: 256m
          cpus: "3.00"


  portainer:
    image: portainer/portainer
    ports:
      - 0.0.0.0:9000:9000
    networks:
      - net_grafana
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    environment:
      TZ: Asia/Shanghai
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 256m
          cpus: "2.00"

networks:
  net_grafana:
    driver: overlay

volumes:
  influx:
    driver: local
  grafana:
    driver: local
  portainer:
    driver: local