version: '3'

# /var/www/html Main folder, needed for updating
# /var/www/html/custom_apps installed / modified apps
# /var/www/html/config local configuration
# /var/www/html/data the actual data of your Nextcloud
# /var/www/html/themes/<YOUR_CUSTOM_THEME> theming/branding

services:
  db:
    image: mariadb
    container_name: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    container_name: nextcloud
    ports:
      - 81:80
    links:
      - db
    volumes:
      - ./data:/var/www/html
    restart: unless-stopped