version: '3'

services:
  teamcity-server:
    image: jetbrains/teamcity-server
    container_name: teamcity-server
    ports:
      - "8111:8111"
    volumes:
      - ./data/datadir:/data/teamcity_server/datadir
      - ./data/logs:/opt/teamcity/logs
    networks:
      - abyssnet
    restart: unless-stopped


  agent:
    image: jetbrains/teamcity-minimal-agent
    container_name: teamcity-agent
    environment:
      - SERVER_URL=http://teamcity:8111
      - AGENT_NAME=abyss-mac
    volumes:
      - ./data/agent/conf:/data/teamcity_agent/conf
    links:
      - teamcity-server
    depends_on:
      - teamcity-server
    networks:
      - abyssnet
    restart: unless-stopped

networks:
  abyssnet:
    driver: bridge